"""
utils/llm_variation_cache.py

Shared helpers for caching LLM-rewritten (structured-variation) prompts.

All experiment files that generate or consume LLM-varied prompts
(length_variation, inter_vs_imper, etc.) should use these functions
so that:
  - cache paths are consistent across experiments
  - caches generated by one script are found by all others
  - JSONL I/O logic lives in exactly one place

Cache layout:
  {data_dir}/llm_variation_cache/{dataset}/{variation}__{param}.jsonl

Each JSONL row:
  {"prompt_orig": "...", "prompt_varied": "...", "variation": "...", "param": "..."}
"""

import json
import os
from typing import Any, List

from tqdm import tqdm


# ------------------------------------------------------------------ #
# Low-level helpers
# ------------------------------------------------------------------ #

def safe_name(x: Any) -> str:
    """Sanitise a value for use in file / directory names."""
    if x is None:
        return "none"
    x = str(x)
    return "".join(c if c.isalnum() or c in ("-", "_", ".", "=") else "_" for c in x)


def write_jsonl(path: str, rows: List[dict]) -> None:
    """Write a list of dicts to a JSONL file, creating parent directories as needed."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")


def read_jsonl(path: str) -> List[dict]:
    """Read a JSONL file and return a list of dicts, skipping blank lines."""
    out: List[dict] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                out.append(json.loads(line))
    return out


# ------------------------------------------------------------------ #
# Cache path
# ------------------------------------------------------------------ #

def variation_cache_path(data_dir: str, dataset: str, variation_name: str, param: str) -> str:
    """
    Canonical cache file for one (dataset, variation, param) combination.

    Example:
        variation_cache_path("data", "harmbench", "length_variation", "2.0")
        → "data/llm_variation_cache/harmbench/length_variation__2.0.jsonl"
    """
    return os.path.join(
        data_dir, "llm_variation_cache",
        safe_name(dataset),
        f"{safe_name(variation_name)}__{safe_name(param)}.jsonl",
    )


def batch_cache_path(data_dir: str, dataset: str, multipliers: List[float]) -> str:
    """
    Cache file for a batch length-variation call (all multipliers in one shot).

    Example:
        batch_cache_path("data", "truthful_qa", [0.5, 1.5, 2.0])
        → "data/llm_variation_cache/truthful_qa/length_variation_batch__0.5_1.5_2.0.jsonl"
    """
    mults_key = "_".join(str(m) for m in sorted(multipliers))
    return os.path.join(
        data_dir, "llm_variation_cache",
        safe_name(dataset),
        f"length_variation_batch__{safe_name(mults_key)}.jsonl",
    )


# ------------------------------------------------------------------ #
# Load-or-generate  (single variation + param)
# ------------------------------------------------------------------ #

def load_or_generate_varied_prompts(
        *,
        data_dir: str,
        dataset: str,
        prompts: List[str],
        variation_name: str,
        param: Any,
        rewrite_provider: str,
        rewrite_model: str,
        rewrite_api_key_env: str,
        overwrite: bool = False,
) -> List[str]:
    """
    Return a list of varied prompts (same length as *prompts*).

    If a matching cache file exists and has the right row count, it is
    loaded directly.  Otherwise the rewrites are generated via the LLM
    and then cached for future runs.

    Works for any structured variation whose ``apply_*`` function is in
    ``utils.variations`` (currently ``length_variation`` and ``inter_vs_imper``).
    """
    from utils.variations import apply_length_variation, apply_interrogative

    cpath = variation_cache_path(data_dir, dataset, variation_name, str(param))

    if not overwrite and os.path.exists(cpath):
        rows = read_jsonl(cpath)
        if len(rows) == len(prompts):
            print(f"  ✓ Loaded varied prompts from cache ({len(rows)} rows): {cpath}")
            return [r["prompt_varied"] for r in rows]

    print(f"  Generating varied prompts ({variation_name}, param={param}) "
          f"via {rewrite_provider}/{rewrite_model} ...")

    varied: List[str] = []
    rows_to_cache: List[dict] = []

    for p in tqdm(prompts, desc=f"  {variation_name}({param})", unit="prompt"):
        if variation_name == "length_variation":
            s = apply_length_variation(
                p, multiplier=float(param),
                provider=rewrite_provider,
                model=rewrite_model,
                api_key_env=rewrite_api_key_env,
            )
        elif variation_name == "inter_vs_imper":
            s = apply_interrogative(
                p, mode=str(param),
                provider=rewrite_provider,
                model=rewrite_model,
                api_key_env=rewrite_api_key_env,
            )
        else:
            raise ValueError(f"Unknown structured variation: {variation_name}")

        varied.append(s)
        rows_to_cache.append({
            "prompt_orig": p,
            "prompt_varied": s,
            "variation": variation_name,
            "param": str(param),
        })

    write_jsonl(cpath, rows_to_cache)
    print(f"  ✓ Cached {len(rows_to_cache)} varied prompts → {cpath}")
    return varied


# ------------------------------------------------------------------ #
# Load-or-generate  (batch: all multipliers in one LLM call)
# ------------------------------------------------------------------ #

def load_or_generate_batch_variations(
        *,
        data_dir: str,
        dataset: str,
        prompts: List[str],
        multipliers: List[float],
        rewrite_provider: str,
        rewrite_model: str,
        rewrite_api_key_env: str,
        overwrite: bool = False,
) -> List[dict]:
    """
    Apply length variation for ALL multipliers in one LLM call per prompt
    via ``apply_length_variation_batch``.

    Returns list of dicts:
        {prompt_orig, prompt_varied, variation, param}
    (one row per prompt × multiplier).
    """
    from utils.variations import apply_length_variation_batch

    cpath = batch_cache_path(data_dir, dataset, multipliers)
    expected_rows = len(prompts) * len(multipliers)

    if not overwrite and os.path.exists(cpath):
        rows = read_jsonl(cpath)
        if len(rows) == expected_rows:
            print(f"  ✓ Loaded from cache ({len(rows)} rows): {cpath}")
            return rows

    print(f"  Generating batch length variations ({multipliers}) "
          f"via {rewrite_provider}/{rewrite_model} ...")

    rows: List[dict] = []
    for p in tqdm(prompts, desc="  length_variation_batch", unit="prompt"):
        results = apply_length_variation_batch(
            p,
            multipliers=multipliers,
            provider=rewrite_provider,
            model=rewrite_model,
            api_key_env=rewrite_api_key_env,
        )
        for m in multipliers:
            rows.append({
                "prompt_orig": p,
                "prompt_varied": results.get(m, p),
                "variation": "length_variation_batch",
                "param": str(m),
            })

    write_jsonl(cpath, rows)
    print(f"  ✓ Cached {len(rows)} rows → {cpath}")
    return rows

