"""
utils/llm_style_cache.py

Shared helpers for caching LLM-rewritten (structured-style) prompts.

All experiment files that generate or consume LLM-varied prompts
(length_variation, interrogative, etc.) should use these functions
so that:
  - cache paths are consistent across experiments
  - caches generated by one script are found by all others
  - JSONL I/O logic lives in exactly one place

Cache layout:
  {data_dir}/llm_style_cache/{dataset}/{style}__{param}.jsonl

Each JSONL row:
  {"prompt_orig": "...", "prompt_styled": "...", "style": "...", "param": "..."}
"""

import json
import os
from typing import Any, List

from tqdm import tqdm


# ------------------------------------------------------------------ #
# Low-level helpers
# ------------------------------------------------------------------ #

def safe_name(x: Any) -> str:
    """Sanitise a value for use in file / directory names."""
    if x is None:
        return "none"
    x = str(x)
    return "".join(c if c.isalnum() or c in ("-", "_", ".", "=") else "_" for c in x)


def write_jsonl(path: str, rows: List[dict]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")


def read_jsonl(path: str) -> List[dict]:
    out: List[dict] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                out.append(json.loads(line))
    return out


# ------------------------------------------------------------------ #
# Cache path
# ------------------------------------------------------------------ #

def style_cache_path(data_dir: str, dataset: str, style_name: str, param: str) -> str:
    """
    Canonical cache file for one (dataset, style, param) combination.

    Example:
        style_cache_path("data", "harmbench", "length_variation", "2.0")
        → "data/llm_style_cache/harmbench/length_variation__2.0.jsonl"
    """
    return os.path.join(
        data_dir, "llm_style_cache",
        safe_name(dataset),
        f"{safe_name(style_name)}__{safe_name(param)}.jsonl",
    )


def batch_cache_path(data_dir: str, dataset: str, multipliers: List[float]) -> str:
    """
    Cache file for a batch length-variation call (all multipliers in one shot).

    Example:
        batch_cache_path("data", "truthful_qa", [0.5, 1.5, 2.0])
        → "data/llm_style_cache/truthful_qa/length_variation_batch__0.5_1.5_2.0.jsonl"
    """
    mults_key = "_".join(str(m) for m in sorted(multipliers))
    return os.path.join(
        data_dir, "llm_style_cache",
        safe_name(dataset),
        f"length_variation_batch__{safe_name(mults_key)}.jsonl",
    )


# ------------------------------------------------------------------ #
# Load-or-generate  (single style + param)
# ------------------------------------------------------------------ #

def load_or_generate_styled_prompts(
        *,
        data_dir: str,
        dataset: str,
        prompts: List[str],
        style_name: str,
        param: Any,
        rewrite_provider: str,
        rewrite_model: str,
        rewrite_api_key_env: str,
        overwrite: bool = False,
) -> List[str]:
    """
    Return a list of styled prompts (same length as *prompts*).

    If a matching cache file exists and has the right row count, it is
    loaded directly.  Otherwise the rewrites are generated via the LLM
    and then cached for future runs.

    Works for any structured style whose ``apply_*`` function is in
    ``utils.styles`` (currently ``length_variation`` and ``interrogative``).
    """
    from utils.styles import apply_length_variation, apply_interrogative

    cpath = style_cache_path(data_dir, dataset, style_name, str(param))

    if not overwrite and os.path.exists(cpath):
        rows = read_jsonl(cpath)
        if len(rows) == len(prompts):
            print(f"  ✓ Loaded styled prompts from cache ({len(rows)} rows): {cpath}")
            return [r["prompt_styled"] for r in rows]

    print(f"  Generating styled prompts ({style_name}, param={param}) "
          f"via {rewrite_provider}/{rewrite_model} ...")

    styled: List[str] = []
    rows_to_cache: List[dict] = []

    for p in tqdm(prompts, desc=f"  {style_name}({param})", unit="prompt"):
        if style_name == "length_variation":
            s = apply_length_variation(
                p, multiplier=float(param),
                provider=rewrite_provider,
                model=rewrite_model,
                api_key_env=rewrite_api_key_env,
            )
        elif style_name == "interrogative":
            s = apply_interrogative(
                p, mode=str(param),
                provider=rewrite_provider,
                model=rewrite_model,
                api_key_env=rewrite_api_key_env,
            )
        else:
            raise ValueError(f"Unknown structured style: {style_name}")

        styled.append(s)
        rows_to_cache.append({
            "prompt_orig": p,
            "prompt_styled": s,
            "style": style_name,
            "param": str(param),
        })

    write_jsonl(cpath, rows_to_cache)
    print(f"  ✓ Cached {len(rows_to_cache)} styled prompts → {cpath}")
    return styled


# ------------------------------------------------------------------ #
# Load-or-generate  (batch: all multipliers in one LLM call)
# ------------------------------------------------------------------ #

def load_or_generate_batch_variations(
        *,
        data_dir: str,
        dataset: str,
        prompts: List[str],
        multipliers: List[float],
        rewrite_provider: str,
        rewrite_model: str,
        rewrite_api_key_env: str,
        overwrite: bool = False,
) -> List[dict]:
    """
    Apply length variation for ALL multipliers in one LLM call per prompt
    via ``apply_length_variation_batch``.

    Returns list of dicts:
        {prompt_orig, prompt_styled, style, param}
    (one row per prompt × multiplier).
    """
    from utils.styles import apply_length_variation_batch

    cpath = batch_cache_path(data_dir, dataset, multipliers)
    expected_rows = len(prompts) * len(multipliers)

    if not overwrite and os.path.exists(cpath):
        rows = read_jsonl(cpath)
        if len(rows) == expected_rows:
            print(f"  ✓ Loaded from cache ({len(rows)} rows): {cpath}")
            return rows

    print(f"  Generating batch length variations ({multipliers}) "
          f"via {rewrite_provider}/{rewrite_model} ...")

    rows: List[dict] = []
    for p in tqdm(prompts, desc="  length_variation_batch", unit="prompt"):
        results = apply_length_variation_batch(
            p,
            multipliers=multipliers,
            provider=rewrite_provider,
            model=rewrite_model,
            api_key_env=rewrite_api_key_env,
        )
        for m in multipliers:
            rows.append({
                "prompt_orig": p,
                "prompt_styled": results.get(m, p),
                "style": "length_variation_batch",
                "param": str(m),
            })

    write_jsonl(cpath, rows)
    print(f"  ✓ Cached {len(rows)} rows → {cpath}")
    return rows

